Add destinations to V3 Routes Struct
cloudfoundry-community/go-cfclient pull request #318
Opened 2022-09-28 10:48 UTC by MB175

The V3Route struct was missing the destination array

2022-09-28 18:17 UTC, sneal requested changes
Thanks for submitting a PR for this, destinations are pretty important in v3. Just a couple of minor changes and I'll merge it.

2022-09-28 18:17 UTC, sneal commented on v3routes.go
> +	Guid string `json:"guid"`
Change to `GUID`

2022-09-28 18:17 UTC, sneal commented on v3routes.go
> +		Guid    string `json:"guid"`
Change to `GUID`

2022-09-28 18:19 UTC, sneal commented
There looks to be a couple of unfortunate usages of 'Guid' even in the v3 structs in this library.

2022-09-29 13:46 UTC, MB175 commented on v3routes.go
> +	Guid string `json:"guid"`
Changed

2022-09-29 13:49 UTC, MB175 commented
> There looks to be a couple of unfortunate usages of 'Guid' even in the v3 structs in this library.

Line 14 also has the Guid filed instead of GUID, I guess this shall not be changed since it would be breaking.

2022-09-30 02:11 UTC, sneal commented
Thanks for the addition and making those GUID changes!

2022-09-30 02:11 UTC, merged